<?php
       
/*
 * Implementation of hook_form_alter()
 */

function custom_example_form_alter(&$form, &$form_state, $form_id){
  // target a single form
  if($form_id == "search_block_form"){
    drupal_set_message("Before : " . $form['search_block_form']['#title']);
    //dsm($form);
  	$form['search_block_form']['#title'] = t('New Form Title');
  }
	drupal_set_message("After : " . $form['search_block_form']['#title']);
	dsm($form);
}